server:
  port: 8080

spring:
  profiles:
    include: param
  datasource:
    url: jdbc:mysql://${HOST}:${MYSQL_PORT}/${MYSQL_DATABASE}?useSSL=false&userUnicode=true&characterEncoding=utf-8
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: ${MYSQL_DRIVER}
  redis:
    host: ${HOST}
    port: ${REDIS_PORT}
    password: ${REDIS_PASSWORD}
    database: 0
    timeout: 3000
mybatis-plus:
  configuration:
    # 数据库表的字段和Java实体类的属性使用驼峰命名进行映射
    map-underscore-to-camel-case: true
    # 启动MyBatis-Plus日志为StdOutImpl
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto #主键自增
      logic-delete-field: showStatus